# Generated by Django 3.1.7 on 2021-03-03 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_alta', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'ordenes',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.IntegerField(unique=True)),
                ('apellido', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_nac', models.DateField()),
                ('fecha_alta', models.DateField(auto_now=True)),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('direccion', models.TextField(blank=True, default=None, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prueba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('minimo', models.FloatField(blank=True, default=None, null=True)),
                ('maximo', models.FloatField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=10)),
                ('descrip', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'unidades',
            },
        ),
        migrations.CreateModel(
            name='Resultados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField(blank=True, default=None, null=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.orden')),
                ('prueba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.prueba')),
            ],
        ),
        migrations.AddField(
            model_name='prueba',
            name='unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.unidad'),
        ),
        migrations.AddField(
            model_name='orden',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.paciente'),
        ),
        migrations.AddField(
            model_name='orden',
            name='pruebas',
            field=models.ManyToManyField(through='lab.Resultados', to='lab.Prueba'),
        ),
    ]
