# Generated by Django 3.1.7 on 2021-03-04 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Resultados',
            new_name='Resultado',
        ),
    ]
