# Generated by Django 3.1.7 on 2021-03-05 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_auto_20210303_2133'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orden',
            options={'verbose_name_plural': 'órdenes'},
        ),
        migrations.AlterField(
            model_name='orden',
            name='fecha_alta',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='direccion',
            field=models.TextField(blank=True, default=None, max_length=255, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fecha_alta',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de ingreso'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fecha_nac',
            field=models.DateField(verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefono',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='prueba',
            name='maximo',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Val. Ref. Máximo'),
        ),
        migrations.AlterField(
            model_name='prueba',
            name='minimo',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Val. Ref. Mínimo'),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='descrip',
            field=models.CharField(max_length=100, verbose_name='Descripción'),
        ),
        migrations.AlterUniqueTogether(
            name='resultado',
            unique_together={('prueba', 'orden')},
        ),
    ]
